### ISSUE TITLE
【bug】1.2.3 版本由于没有做好兼容处理导致报错

### ISSUE THREAD

**Issue by liujuping** [recore/recore#17]
循环+条件场景下，部分组件由于未渲染，获取到的 view 为 null，在这种情况下，这里执行改代码会出现兼容问题。

https://github.com/recore/recore/blob/feat/get-view-batch-api/packages/recore-core/src/view-controller.ts#L201

相当于 null.$ref，导致页面出现报错。

![image](https://user-images.githubusercontent.com/11935995/190425698-e7ef38b2-5d73-4262-a041-36da44d0165d.png)

问题：
1.目前是在 feat/get-view-batch-api 分支看到的代码，后续需要合并到哪个分支？

2.版本的发布可以找谁？

**Comment by AlbertXiao1994** [comment]
#18 fix
